[package]
name = "scavanger"
version = "0.1.0"
authors = ["AliusDieMorietur <ikamqwert@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.6.2"
console = "0.11.2"
